version: '2'

services:
  web:
    build: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
    links:
      - db:db

  db:
    image: "mysql:5.6"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
